version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo Building Lambda function for search-photos...
      - cd search-photos
      - zip -r ../search-photos.zip .
      - cd ..
      - echo Building Lambda function for index-photos...
      - cd index-photos
      - zip -r ../index-photos.zip .
      - cd ..
      - echo Uploading packages to S3...
      - aws s3 cp search-photos.zip s3://lambda-build-photo-album/search-photos.zip
      - aws s3 cp index-photos.zip s3://lambda-build-photo-album/index-photos.zip
  post_build:
    commands:
      - echo Deploying to Lambda...
      - aws lambda update-function-code --function-name search-photos --s3-bucket lambda-build-photo-album --s3-key search-photos.zip
      - aws lambda update-function-code --function-name index-photos --s3-bucket lambda-build-photo-album --s3-key index-photos.zip